# Numpy

In [9]:
import numpy as np
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

In [15]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [6]:

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
type(x)

numpy.ndarray

In [14]:
x.shape

(2, 3)

In [16]:
x.ndim

2

In [17]:
x.size

6

In [18]:
x.dtype

dtype('int64')

In [20]:
x.nbytes

48

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

In [24]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(x)
print(x.nbytes)


[[1. 2. 3.]
 [4. 5. 6.]]
48


In [26]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
print(x)
print(x.nbytes)


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [28]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.uint32)
print(x)
print(x.nbytes)

[[1 2 3]
 [4 5 6]]
24


In [29]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(x.nbytes, "bytes")

48 bytes


In [30]:

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print( x.nbytes, "bytes")

24 bytes


In [33]:

x_copy = np.array(x, dtype=float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:

x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:

x_copy


array([[1., 2., 3.],
       [4., 5., 6.]])

# Операции с массивами

In [37]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [38]:
my_array

array([ 2, 14,  6,  8])

In [41]:

my_array + 2


array([ 4, 16,  8, 10])

In [42]:

my_array - 1

array([ 1, 13,  5,  7])

In [43]:

my_array * 2

array([ 4, 28, 12, 16])

In [44]:

my_array / 2

array([1., 7., 3., 4.])

In [46]:

second_array = np.zeros(4) + 3
second_array

array([3., 3., 3., 3.])

In [48]:
my_array


array([ 2, 14,  6,  8])

In [47]:
my_array - second_array


array([-1., 11.,  3.,  5.])

In [ ]:

second_array / my_array

In [52]:

second_array = np.ones(4) + 3
second_array

array([4., 4., 4., 4.])

In [53]:

my_array - second_array


array([-2., 10.,  2.,  4.])

In [54]:

second_array / my_array

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [55]:

second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:

second_array = np.identity(4) + 3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [58]:
my_array

array([ 2, 14,  6,  8])

In [59]:

my_array - second_array

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [60]:

second_array / my_array

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [61]:

x = np.arange(3, 7, 0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [64]:

x = np.linspace(1.2, 40.5, num=1000)
x

array([ 1.2       ,  1.23933934,  1.27867868,  1.31801802,  1.35735736,
        1.3966967 ,  1.43603604,  1.47537538,  1.51471471,  1.55405405,
        1.59339339,  1.63273273,  1.67207207,  1.71141141,  1.75075075,
        1.79009009,  1.82942943,  1.86876877,  1.90810811,  1.94744745,
        1.98678679,  2.02612613,  2.06546547,  2.1048048 ,  2.14414414,
        2.18348348,  2.22282282,  2.26216216,  2.3015015 ,  2.34084084,
        2.38018018,  2.41951952,  2.45885886,  2.4981982 ,  2.53753754,
        2.57687688,  2.61621622,  2.65555556,  2.69489489,  2.73423423,
        2.77357357,  2.81291291,  2.85225225,  2.89159159,  2.93093093,
        2.97027027,  3.00960961,  3.04894895,  3.08828829,  3.12762763,
        3.16696697,  3.20630631,  3.24564565,  3.28498498,  3.32432432,
        3.36366366,  3.403003  ,  3.44234234,  3.48168168,  3.52102102,
        3.56036036,  3.5996997 ,  3.63903904,  3.67837838,  3.71771772,
        3.75705706,  3.7963964 ,  3.83573574,  3.87507508,  3.91

In [65]:

np.geomspace(1, 625, num=5)



array([  1.,   5.,  25., 125., 625.])

In [67]:

np.logspace(3, 4, num=100)


array([ 1000.        ,  1023.5310219 ,  1047.61575279,  1072.26722201,
        1097.49876549,  1123.32403298,  1149.7569954 ,  1176.81195243,
        1204.50354026,  1232.84673944,  1261.85688307,  1291.54966501,
        1321.94114847,  1353.04777458,  1384.88637139,  1417.47416293,
        1450.8287785 ,  1484.96826225,  1519.91108295,  1555.67614393,
        1592.28279334,  1629.75083462,  1668.1005372 ,  1707.35264747,
        1747.52840001,  1788.64952906,  1830.7382803 ,  1873.81742286,
        1917.91026167,  1963.04065004,  2009.23300257,  2056.51230835,
        2104.90414451,  2154.43469003,  2205.1307399 ,  2257.01971963,
        2310.12970008,  2364.48941265,  2420.12826479,  2477.07635599,
        2535.36449397,  2595.0242114 ,  2656.08778295,  2718.58824273,
        2782.55940221,  2848.03586844,  2915.05306283,  2983.64724028,
        3053.85550883,  3125.71584969,  3199.2671378 ,  3274.54916288,
        3351.60265094,  3430.46928631,  3511.19173422,  3593.8136638 ,
      

In [68]:

np.logspace(np.log10(3), np.log10(4), num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [69]:

x = np.array([1, 2, 3, 4])
y = np.array([1, 3, 4, 4])

In [70]:

x == y


array([ True, False, False,  True])

In [72]:

x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])
np.array_equal(x, y)

True

In [73]:

x = np.array([1, 2, 3, 4])
y = np.array([1, 3, 4, 4])
x < y

array([False,  True,  True, False])

In [74]:

x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)

In [75]:
x

array([False,  True, False, False])

In [76]:

np.logical_or(x, y)

array([ True,  True, False,  True])

In [78]:

np.logical_and(x, y)

array([False,  True, False, False])

In [79]:

x = np.array([12, 16, 57, 11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [80]:

x = np.array([1, 2, 3, 4])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [81]:

np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [82]:

np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [83]:

x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [85]:

x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:

x.T


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [93]:
x = np.arange(6).reshape(2, 3)

In [94]:

x.T
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:

np.sum(x)

36

In [96]:

np.amin(x)

0

In [98]:

np.amax(x)

8

In [99]:

np.amin(x, axis=0)

array([0, 1, 2])

In [100]:

np.amin(x, axis=1)

array([0, 3, 6])

In [105]:

np.percentile(x, 99)

7.92

In [106]:

x = np.array([1, -21, 3, -3])

In [107]:

np.argmax(x)

2

In [108]:

np.argmin(x)

1

In [109]:

x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [110]:

np.mean(x)

7.666666666666667

In [112]:

np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [113]:

np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [115]:
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [114]:

np.median(x)

4.5

In [116]:

np.std(x)

6.394442031083626

# Многомерные массивы

In [117]:
c = np.ones((4, 4))

In [118]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [119]:

c * c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [120]:

c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [121]:

y = np.arange(15).reshape(3, 5)
x = np.arange(10).reshape(2, 5)

In [123]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [124]:

new_array = np.vstack((y, x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [126]:

y = np.arange(15).reshape(5, 3)
x = np.arange(10).reshape(5, 2)

In [128]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [129]:

new_array = np.hstack((y, x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [130]:

from scipy import stats

x = np.random.rand(100, 10)


In [134]:

n, min_max, mean, var, skew, kurt = stats.describe(x)

In [136]:

new_array = np.vstack((mean, var, skew, kurt, min_max[0], min_max[1]))

In [137]:
new_array

array([[ 5.05229338e-01,  4.89832091e-01,  5.00241168e-01,
         4.83705185e-01,  4.57991725e-01,  4.82256423e-01,
         4.96737642e-01,  4.96725839e-01,  4.87732323e-01,
         4.98888483e-01],
       [ 7.92788287e-02,  8.27135724e-02,  8.50388191e-02,
         8.56676833e-02,  7.45612874e-02,  7.39789046e-02,
         7.19017326e-02,  8.53095320e-02,  7.16385266e-02,
         1.01433845e-01],
       [-1.09479276e-01,  8.96744843e-02, -5.37917668e-03,
         1.55797928e-01,  1.02169166e-01,  2.47331044e-01,
         1.59577377e-01,  2.50986551e-02, -4.15350460e-02,
        -2.63667191e-02],
       [-1.12139701e+00, -1.20645481e+00, -1.29763877e+00,
        -1.26373695e+00, -1.16785176e+00, -1.07757602e+00,
        -1.04068592e+00, -1.35106968e+00, -9.94601664e-01,
        -1.45130134e+00],
       [ 6.84812877e-03,  1.82197452e-03,  7.91891054e-03,
         2.43447581e-02,  1.66479379e-02,  7.76885650e-03,
         9.28352754e-05,  3.58178844e-03,  1.54848697e-03,
         2.

In [ ]:

new_array.T


# Индексы и слайсы

In [138]:
x = ["USA", "France", "Germany", "England"]
x[2]

'Germany'

In [139]:

x = ('USA', 3, "France", 4)
x[2]

'France'

In [140]:

x = np.arange(10)

In [141]:

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:

x[5]

5

In [145]:

x[-2]

8

In [146]:

x[2:8]

array([2, 3, 4, 5, 6, 7])

In [147]:

x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:

x[2:8:2]


array([2, 4, 6])

In [150]:

x = np.reshape(np.arange(16), (4, 4))

In [151]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [152]:

x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:

x[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [154]:

x[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [155]:

x = np.reshape(np.arange(16), (4, 4))

In [156]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:

x[[0, 1, 2], [0, 1, 3]]

array([ 0,  5, 11])

In [162]:

x = np.arange(16).reshape(4, 4)

In [163]:

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [164]:

np.resize(x, (2, 2))

array([[0, 1],
       [2, 3]])

In [165]:

np.resize(x, (6, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [169]:

x = np.arange(16).reshape(4, 4)

In [170]:

y = np.arange(6).reshape(2, 3)

In [171]:

x + y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [173]:

x = np.ones(16).reshape(4, 4)

In [174]:

y = np.arange(4)

In [175]:

x * y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [176]:

x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [182]:

y = np.arange(2).reshape(1, 2)
y

array([[0, 1]])

In [181]:

x * y

ValueError: operands could not be broadcast together with shapes (2,2) (1,4) 